FROM python:3.9

# set a directory for the app
WORKDIR /usr/src/app

# copy files to the application
COPY . .

# install dependencies
RUN pip install -r requirements.txt

# run the application
# CMD ["python", "my_script.py"]